# 应用名称
spring:
  application:
    name: seata-business
#数据库配置
  datasource:
     url: jdbc:mysql://localhost:3306/crm?useSSL=false&serverTimezone=UTC
     username: root
     password: 7923
server:
  port: 7901

#eureka实例注册
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/













